# Generated by Django 2.2 on 2020-03-18 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH', models.FloatField(verbose_name='ph值')),
                ('DO', models.FloatField(verbose_name='溶解氧')),
                ('CODMn', models.FloatField(verbose_name='CODMn')),
                ('NH3_N', models.FloatField(verbose_name='NH2-N')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': '水质数据',
                'verbose_name_plural': '水质数据',
            },
        ),
    ]
