# Generated by Django 2.2 on 2020-03-24 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.FloatField(verbose_name='温度')),
                ('Po', models.FloatField(verbose_name='气象站水平大气压')),
                ('P', models.FloatField(verbose_name='平均大气压')),
                ('U', models.FloatField(verbose_name='湿度-N')),
                ('Ff', models.FloatField(verbose_name='风速')),
                ('VV', models.FloatField(verbose_name='水平能见度')),
                ('Td', models.FloatField(verbose_name='露点温度')),
                ('RRR', models.FloatField(verbose_name='降水量')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': '气象数据',
                'verbose_name_plural': '气象数据',
            },
        ),
    ]
